JOB_NAMES = (
    "gig",
    "role",
    "part",     # careful with this one
    "position",
)


GENDERS = (('N', ''), ('M', 'Male'), ('F', 'Female'))


UK_PLACES = (

    ("", ""),
    ("Aberdeen", "Aberdeen"),
    ("Armagh", "Armagh"),
    ("Bangor", "Bangor"),
    ("Bath", "Bath"),
    ("Belfast", "Belfast"),
    ("Birmingham", "Birmingham"),
    ("Bradford", "Bradford"),
    ("BrightonH", "Brighton and Hove"),
    ("Bristol", "Bristol"),
    ("Cambridge", "Cambridge"),
    ("Canterbury", "Canterbury"),
    ("Cardiff", "Cardiff"),
    ("Carlisle", "Carlisle"),
    ("Chester", "Chester"),
    ("Chichester", "Chichester"),
    ("Coventry", "Coventry"),
    ("Derby", "Derby"),
    ("Dundee", "Dundee"),
    ("Durham", "Durham"),
    ("Edinburgh", "Edinburgh"),
    ("Ely", "Ely"),
    ("Exeter", "Exeter"),
    ("Glasgow", "Glasgow"),
    ("Gloucester", "Gloucester"),
    ("Hereford", "Hereford"),
    ("Inverness", "Inverness"),
    ("KingstonUH", "Kingston upon Hull"),
    ("Lancaster", "Lancaster"),
    ("Leeds", "Leeds"),
    ("Leicester", "Leicester"),
    ("Lichfield", "Lichfield"),
    ("Lincoln", "Lincoln"),
    ("Lisburn", "Lisburn"),
    ("Liverpool", "Liverpool"),
    ("London", "London"),
    ("Londonderry", "Londonderry"),
    ("Manchester", "Manchester"),
    ("NewcastleUT", "Newcastle upon Tyne"),
    ("Newport", "Newport"),
    ("Newry", "Newry"),
    ("Norwich", "Norwich"),
    ("Nottingham", "Nottingham"),
    ("Oxford", "Oxford"),
    ("Peterborough", "Peterborough"),
    ("Plymouth", "Plymouth"),
    ("Portsmouth", "Portsmouth"),
    ("Preston", "Preston"),
    ("Ripon", "Ripon"),
    ("Salford", "Salford"),
    ("Salisbury", "Salisbury"),
    ("Sheffield", "Sheffield"),
    ("Southampton", "Southampton"),
    ("StAlbans", "StAlbans"),
    ("StDavids", "StDavids"),
    ("Stirling", "Stirling"),
    ("Stoke-on-Trent", "Stoke-on-Trent"),
    ("Sunderland", "Sunderland"),
    ("Swansea", "Swansea"),
    ("Swindon", "Swindon"),
    ("Truro", "Truro"),
    ("Wakefield", "Wakefield"),
    ("Wells", "Wells"),
    ("Winchester", "Winchester"),
    ("Wolverhampton", "Wolverhampton"),
    ("Worcester", "Worcester"),
    ("York", "York"),

)
